server:
  port: 9010
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

alibaba-api-key: ${alibaba_key}
spring:
  data:
    redis:
      host: localhost
      password: qwe123
      port: 6379
